package com.example.bankcards;

import com.example.bankcards.util.Utility;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.sql.Date;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * The rest of the suite runs on H2, whose schema is generated by Hibernate and
 * therefore has none of the constraints the Flyway migrations create — no
 * foreign key, no status check, no unique username. Those invariants exist only
 * in production, so they are verified here against the real database engine.
 *
 * <p>Each test rolls back, so repeated runs are safe.
 */
@Transactional
class PostgresSchemaIntegrationTest extends PostgresIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private Utility utility;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @PersistenceContext
    private EntityManager entityManager;

    private void insertCard(String id, String numberHash, String holderId, String status, BigDecimal balance) {
        jdbcTemplate.update(
                """
                        INSERT INTO card (id, number, number_hash, holder_id, status, balance, expiration_date, version)
                        VALUES (?, ?, ?, ?, ?, ?, ?, 0)
                        """,
                id, "ciphertext", numberHash, holderId, status, balance, Date.valueOf("2030-01-01")
        );
    }

    @Test
    void flywayMigrationsBuildASchemaTheEntitiesValidateAgainst() {
        // Reaching this point already proves ddl-auto=validate accepted the
        // migrated schema, otherwise the context would not have started.
        Integer applied = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM flyway_schema_history WHERE success = true",
                Integer.class
        );

        assertThat(applied).isGreaterThanOrEqualTo(4);
    }

    @Test
    void holderIdForeignKeyIsEnforced() {
        assertThatThrownBy(() -> insertCard(
                "card-bad-holder", "hash-bad-holder", "no-such-user", "ACTIVE", BigDecimal.TEN
        )).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void unknownHolderIsRejectedByTheApiBeforeReachingTheConstraint() throws Exception {
        String adminToken = utility.loginAdmin(mockMvc);

        // Without the service-level check this is a foreign key failure, which
        // the H2 tests cannot reproduce because H2 has no foreign key here.
        utility.createCardAction(mockMvc, adminToken, 1, "no-such-user", BigDecimal.TEN)
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.detail").value("Card holder does not exist"));
    }

    @Test
    void cardStatusCheckConstraintRejectsUnknownValues() throws Exception {
        String adminToken = utility.loginAdmin(mockMvc);
        String holderId = utility.registerUser(mockMvc, adminToken, "pg-status", "pw");
        String cardId = utility.createCard(mockMvc, adminToken, 2, holderId, BigDecimal.TEN);
        entityManager.flush();

        assertThatThrownBy(() -> jdbcTemplate.update(
                "UPDATE card SET status = 'NOT_A_STATUS' WHERE id = ?", cardId
        )).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void duplicateNumberHashIsRejectedByTheUniqueConstraint() throws Exception {
        String adminToken = utility.loginAdmin(mockMvc);
        String holderId = utility.registerUser(mockMvc, adminToken, "pg-hash", "pw");
        entityManager.flush();

        insertCard("card-hash-1", "duplicate-hash", holderId, "ACTIVE", BigDecimal.TEN);

        // The service pre-checks duplicates, but the constraint is what protects
        // the invariant when two requests race.
        assertThatThrownBy(() -> insertCard(
                "card-hash-2", "duplicate-hash", holderId, "ACTIVE", BigDecimal.TEN
        )).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void duplicateUsernameIsRejectedByTheUniqueConstraint() throws Exception {
        String adminToken = utility.loginAdmin(mockMvc);
        utility.registerUser(mockMvc, adminToken, "pg-duplicate", "pw");
        entityManager.flush();

        assertThatThrownBy(() -> jdbcTemplate.update(
                "INSERT INTO users (id, username, password, role) VALUES (?, ?, ?, ?)",
                "user-duplicate", "pg-duplicate", "hash", "USER"
        )).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void balanceColumnSilentlyRoundsToTwoDecimals() throws Exception {
        String adminToken = utility.loginAdmin(mockMvc);
        String holderId = utility.registerUser(mockMvc, adminToken, "pg-money", "pw");
        entityManager.flush();

        insertCard("card-money", "hash-money", holderId, "ACTIVE", new BigDecimal("10.005"));

        BigDecimal stored = jdbcTemplate.queryForObject(
                "SELECT balance FROM card WHERE id = ?", BigDecimal.class, "card-money"
        );

        // NUMERIC(38,2) rounds instead of failing, which is why the API refuses
        // amounts with more than two decimals: rounding here would create money.
        assertThat(stored).isEqualByComparingTo("10.01");
    }
}
